-- MySQL Script generated by MySQL Workbench
-- Wed Apr  6 20:35:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Prestador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prestador` (
  `idPrestador` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cpf_cnpj` CHAR(14) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Telefone` VARCHAR(15) NULL,
  `Endereco` VARCHAR(100) NULL,
  PRIMARY KEY (`idPrestador`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Cpf` CHAR(11) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Telefone` VARCHAR(15) NULL,
  `Endereco` VARCHAR(100) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serviço` (
  `idServiço` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Setor` VARCHAR(45) NOT NULL,
  `Valor` FLOAT NOT NULL DEFAULT 0,
  `Descricao` VARCHAR(300) NULL,
  `TempoExecucao` INT NULL DEFAULT 0,
  PRIMARY KEY (`idServiço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`presta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`presta` (
  `idPrestador` INT NOT NULL,
  `idServico` INT NOT NULL,
  PRIMARY KEY (`idPrestador`, `idServico`),
  CONSTRAINT `idPrestador`
    FOREIGN KEY (`idPrestador`)
    REFERENCES `mydb`.`Prestador` (`idPrestador`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idServico`
    FOREIGN KEY (`idServico`)
    REFERENCES `mydb`.`Serviço` (`idServiço`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contato` (
  `idPrestador` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `idServico` INT NOT NULL,
  PRIMARY KEY (`idPrestador`, `idCliente`, `idServico`),
  CONSTRAINT `idPrestador`
    FOREIGN KEY (`idPrestador`)
    REFERENCES `mydb`.`presta` (`idPrestador`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idServico`
    FOREIGN KEY (`idServico`)
    REFERENCES `mydb`.`presta` (`idServico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agendamento` (
  `idAgendamento` INT NOT NULL,
  `idServico` INT NOT NULL,
  `idPrestador` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `Data_Horario` DATETIME NOT NULL,
  PRIMARY KEY (`idAgendamento`, `idServico`, `idPrestador`, `idCliente`),
  CONSTRAINT `idServico`
    FOREIGN KEY (`idServico`)
    REFERENCES `mydb`.`contato` (`idServico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`contato` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idPrestador`
    FOREIGN KEY (`idPrestador`)
    REFERENCES `mydb`.`contato` (`idPrestador`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
